### ISSUE TITLE
Add support for biometric

### ISSUE THREAD

**Issue by M3DZIK** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#101]
Support for the use of a fingerprint or face scan when logging into the app could be added. Which would make logging into the app easier.

![image](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/87065584/9136b920-e343-4322-9f3d-9dc4470fef3c)

If we are using Android KeyStore for login then you can use BIOMETRIC_STRONG then you can decrypt the key from it, BIOMETRIC_WEAK does not use cryptography but allows you to unlock with your face as well.

![image](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/87065584/ccdb8b35-00b5-4ab3-b368-6a2be7b3b4c6)

**Comment by stzouvaras** [comment]
Hi @M3DZIK ,

The application already supports biometrics, but they are currently disabled (to be reviewed soon). You can enable them by going to the authentication-logic module and editing the PrefsBiometryStorageProvider.

`    override fun getUseBiometricsAuth(): Boolean {
        return prefsController.getBool("UseBiometricsAuth", false)
    }`
