### ISSUE TITLE
Why the app does not follow the system theme?

### ISSUE THREAD

**Issue by M3DZIK** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#103]
Why does the app have its own theme and not use the system theme? 

Since Android 12 Material3 generates color palettes from the wallpaper and uses this color palette in the system and apps. So system apps as well as other apps can have the same color palettes which is a cool option and in my opinion these colors from material3 look better than the current ones in the app.

<img src="https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/87065584/bb499d15-ce8d-4d9a-b1e6-e138cbc53095" width="300px" />

<img src="https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/87065584/7ec6c9ad-adff-4928-94a0-b4af588d0c7f" width="300px" />

Some other applications (mail app, browser, dialer, librepass):

<img src="https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/87065584/ae18077e-b904-4755-95ac-933bc9a7ad4a" width="300px" />

<img src="https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/87065584/cf83a061-afee-40dc-9cd8-ebb101785e82" width="300px" />

<img src="https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/87065584/412ec38b-8104-4746-a9e9-0fad45f6f854" width="300px" />

<img src="https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/87065584/1ea6bd26-e27c-4f80-b62a-0bd9ec8be32e" width="300px" />

**Comment by stzouvaras** [comment]
Hi @M3DZIK ,

The reference implementation was based on a specific color palette and design system. The wallet offers dynamic theming, configurable to match your needs. You can adjust everything to your liking by editing ThemeColors, ThemeShapes, and ThemeTypography inside the resources-logic module.
