### ISSUE TITLE
Issue with National Id

### ISSUE THREAD

**Issue by dariocast** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#105]
I have the current issue.
When using the provided apk, the internal issuance flow works. 
When building the application from source from branch main, I get 
![Screenshot_2024-05-27-12-14-00-76_70ee39eb6c6907746430475bc561605b](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/15170161/41b8896a-1c3a-4fce-9e81-f9040d75dd98)
when trying to get National Id (the sample documents works as expected.
This error appears both with DEV and DEMO flavor without customization.
I cannot find the point in code in which this part is called, I suppose is internal in the core modules.

**Comment by stzouvaras** [comment]
Hi @dariocast ,

The source code with the Dev flavor selected works as expected. 

Can you please try again with the latest updates from the main branch and let us know? 

The Demo flavor doesn't work at the moment because it's pointing to the production issuer, which is still draft 12. We are working on updating it soon.

**Comment by dariocast** [comment]
Hi, I selected the Dev flavor and the error message when tapping on National ID states now:

> java.net.UnknownHostException: Unable to resolve host "dev.issuer.eudiw.dev": No address associated with hostname

The object managing the variables has not been touched and is:

```kotlin
private companion object {
        const val OPENID4VP_VERIFIER_API_URI = "https://dev.verifier.eudiw.dev"
        const val OPENID4VP_VERIFIER_LEGAL_NAME = "EUDI Remote Verifier"
        const val OPENID4VP_VERIFIER_CLIENT_ID = "Verifier"
        const val VCI_ISSUER_URL = "https://dev.issuer.eudiw.dev"
        const val VCI_CLIENT_ID = "wallet-dev"
        const val AUTHENTICATION_REQUIRED = false
    }
```

**Comment by stzouvaras** [comment]
Hi @dariocast,

the url works for me and it’s publicly accessible. I think there may be something wrong with your network connection or something is blocking this url, maybe some kind of organization filtering or firewall or proxy, not sure.

**Comment by dariocast** [comment]
May I be off-topic here but, is there a public accessible endpoint for the issuer in order to test the QR code? I mean a public accessible backend with a UI similar to the one released [here](https://github.com/eu-digital-identity-wallet/eudi-srv-pid-issuer)

**Comment by stzouvaras** [comment]
Hi @dariocast,

yes there is : https://dev.issuer-backend.eudiw.dev/

**Comment by stzouvaras** [comment]
Closing this issue as resolved, please let us know if there's anything @dariocast
