### ISSUE TITLE
Current code not working with the latest Kotlin issuer

### ISSUE THREAD

**Issue by elblasto420** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#138]
After mounting the Kotlin issuer and trying to connect to it with the latest code on main the app won't go beyond the first 2 endpoints, giving us an error
Apparently it seems to complain that one of the lines inside the CWT JSON is a negative number (-7) and its expecting a String, as such:
![image](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/22560149/5446c4d8-cb88-431b-9d0c-0a961216675c)
And as seen on the JSON:
![image](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/22560149/73b0e36d-4e9b-4256-b7fc-241c310acb64)

![image](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/22560149/704c029e-67a9-4343-8522-c1088b5af4aa)
For some reason, when hitting https://dev.issuer.eudiw.dev it seems to work fine with the same code in the current code
Maybe we are missing scope coverage for the configurations in the libraries?
These are the conf scopes for https://dev.issuer.eudiw.dev
![image](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/22560149/6f6740f5-a60e-4a7e-a768-c943607e4c3d)
And this are the conf scopes for the latest build/code in the kotlin issuer
![image](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/22560149/94b79f81-1ff0-4a13-b72e-815846541b5d)

Any help would be appreciated

**Comment by stzouvaras** [comment]
Hi @elblasto420,

can you please retry with the latest android source code?

**Comment by elblasto420** [comment]
Hi @stzouvaras it works perfectly now! We mounted the latest issuer in Kotlin along the latest code we have in Android and its working perfectly! Thank you!
