### ISSUE TITLE
Pin keyboard closes when using hardware keyboard 

### ISSUE THREAD

**Issue by roffel** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#140]
The keyboard closes when entering the PIN in the emulator with a hardware keyboard.  Impacting user experience and accessibility. 

See video.

https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/9349165/2868259a-59b4-4520-bf4c-35ff342adbaa

Expected behaviour:

Automatically focus on the next input when entering a digit.

**Comment by stzouvaras** [comment]
Hi @roffel,

The hardware keyboard mostly affects emulators because they run on computers with existing keyboards. There may also be some cases involving real devices, particularly those with Bluetooth keyboards, but these are rare.

We will investigate and get back to you as soon as possible.
