### ISSUE TITLE
Error when scanning Credential Offer QR Code

### ISSUE THREAD

**Issue by ielaslaoui** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#148]
Installed Android Version 2024.06.12-Demo linked from README to a Xiaomi 11T Pro with Android 13.

Go to : https://issuer.eudiw.dev/credential_offer_choice
Issue Credential Offer QR code

When scanning code, i'v got error : Unable to fetch and process the credential offer
![Screenshot_2024-07-16-14-46-45-448_eu europa ec euidi](https://github.com/user-attachments/assets/caeabd56-b6b7-417d-a575-9dff5de63161)

**Comment by stzouvaras** [comment]
Hi @ielaslaoui,

can you please provide more information? Which option(s) did you select on the issuer? e.g. eu.europa.ec.eudi.loyalty_mdoc

**Comment by ielaslaoui** [comment]
Hi @stzouvaras 
Yes of course. I've selected this option "eu.europa.ec.eudi.pid_jwt_vc_json"

**Comment by stzouvaras** [comment]
Hi @ielaslaoui 

SD-JWT VC is not currently supported, only mso_mdoc that's why it doesn't work for you.

Please select a mso_mdoc document to issue.

**Comment by ielaslaoui** [comment]
Ok thanks
