### ISSUE TITLE
How to add an own screen?

### ISSUE THREAD

**Issue by victorjaviermartin** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#238]
Hi, this is not an issue, this is a question to know if there are any steps to add a screen to introduce some data to another backend, like... after the QuickPin screen, to introduce a Custom Screen to add an invitation/authorization code to check over another backend?

I feel lost trying to add some screen in that point.

Any advantages?

**Comment by stzouvaras** [comment]
Hi @victorjaviermartin ,

Unfortunately, there is no such way. The flows are predefined and cannot be manipulated without altering the source code. There is no configuration available for this.

**Comment by victorjaviermartin** [comment]
thank you for answer @stzouvaras
