### ISSUE TITLE
mdoc verifier stuck at "Device engagement received..."

### ISSUE THREAD

**Issue by agdolla** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#44]
Installed Android Version 2024.02.1-Demo (3) linked from README to a Samsung A13 5G with Android 14. Installed mDoc Verifier (Testing) Version 1.8 (9) also linked from README to a Samsung A40 with Android 11.
When trying to verify anything the Verifier is stuck at "Device engagement received..." both with NFC and QR code. NFC and Bluetooth are enabled on both devices.

**Comment by stzouvaras** [comment]
Hi @agdolla,

Looking at your device's specs, I noticed that the Samsung A13 has NFC, but it is region-market locked. Are you sure your phone supports NFC and that it works as expected? Have you used it before for anything else?

**Comment by agdolla** [comment]
Hi @stzouvaras,
NFC on A13 works, I've just tried and with an application called readid I could read my id card just fine.
I did not deny any permissions, currently it has only one permission: nearby devices.
![Screenshot_20240308_091928_Permission controller](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/1113987/2a380945-0f49-4bbf-aed2-6c69bd708d1d)

App Verifier has no permission at all, I did not deny any permissons.

Without NFC and using QR code only and bluetooth it still does not work.

**Comment by stzouvaras** [comment]
Hi @agdolla,

The Verifier app should ask for permissions. Please check my screenshots. Can you please check the verifier's permission screen?

![verifier_ask](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/129499766/899ffdaf-dda5-47ad-aa50-8898bc41a8a6)
![verifier_ask2](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/129499766/4a71309b-9ecb-477d-9ac9-c7df542bbdda)
![verifier_perms](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/129499766/39e23b1e-c645-42cf-8743-0818e078dfc4)

**Comment by agdolla** [comment]
Installed the App Verifier on A13/Android14 and it did ask for permissions. On Android11 it did not. It might be my phone or Android11 issue so I'll install a fresh Android11 into an emulator just to find out. Not that I insist using Android11 but one of my test phones runs it.

**Comment by stzouvaras** [comment]
Thank you @agdolla, we will investigate further and revert.

**Comment by stzouvaras** [comment]
Hi @elblasto420,

"Our verifier application is a modified version of the repository you've mentioned. Unfortunately, the code is not publicly accessible. However, there are plans to build and release a new verifier app that will be completely open-source and available to the public, though I cannot provide an ETA at the moment.

**Comment by stzouvaras** [comment]
Hi @agdolla,

This issue will be closed because a new verifier application is underway, and the current one will be replaced.

You can find more information here: https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/blob/main/wiki/verifier_proximity.md

**Comment by agdolla** [comment]
thanks @stzouvaras I will try it
