### ISSUE TITLE
Missing QR-initiated issuance flow

### ISSUE THREAD

**Issue by Detzy** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#58]
There are published repositories for issuing to the wallet using QR codes (see [Issuer Repository](https://github.com/eu-digital-identity-wallet/eudi-srv-pid-issuer) and [Online Implementation](https://issuer-backend.eudiw.dev/issuer/credentialsOffer/generate)). However, the wallet does not seem to support this flow yet. 

I was wondering if this is work in progress? Would a pull request for an implementation be of use, or would I be wasting my time doing something you already have well on the way?

**Comment by stzouvaras** [comment]
Hello @Detzy 

This feature is already on our backlog.

**Comment by stzouvaras** [comment]
Hi @Detzy,

the development has started for draft 13 support and credential offer. The plan is to release the ecosystem and the wallet apps by the end of June.

You can follow these 2 issues:
- https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/issues/72
- https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/issues/73
