### ISSUE TITLE
Unable to issue any VCs - Credentials Supported Required

### ISSUE THREAD

**Issue by Detzy** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#92]
With the newest version, I am unable to issue any credentials at all. 
The error message in the app is a CredentialIssuerMetadataValidationError$CredentialsSupportedRequired,
however the default issuer does in fact make "credentials_supported" available at:
https://issuer.eudiw.dev/oidc/.well-known/openid-credential-issuer

To reproduce:

1. Clone this repo
2. Run application without edits on android device. I have tested both a physical phone and a simulated Pixel 8 API 30.
3. Launch app and make pin. 
4. Press "National ID" button to attempt adding a PID VC.
5. The error should now display as: "Oups! Something went wrong java.lang.illegalArgumentException: Credentials Supported Required"

**Comment by stzouvaras** [comment]
Hello @Detzy 

Please refer to this issue: https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/issues/91
