### ISSUE TITLE
Remove tracking

### ISSUE THREAD

**Issue by Jak2k** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#95]
Firebase crashlytics is installed in the application. This is not required for the application to work. It should be completely removed.

**Comment by stzouvaras** [comment]
Hi @Jak2k ,

The project doesn't use any Firebase tools. There is a convention plugin called "eudi.android.application.firebase," but it is not currently in use. The reason we haven't removed it is in case someone wants to utilize it in the future. The same goes for us; we may need to use it internally for our operations. It doesn't affect the application. 

Have you identified any other issues that affect the application?

**Comment by Jak2k** [comment]
As you can see in [gradel's library config](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/blob/437ca7ab42e121586dcfd2ce3a3fa6494dcba370/gradle/libs.versions.toml#L36), there is firebase analytics included in the project. This is tracking. If the firebase is not being used, that library should be completely removed. There is no valid reason to include a tracking library. When it would be needed in the future, it could be added again.

**Comment by stzouvaras** [comment]
Unfortunately, Microsoft AppCenter is currently being used as well for internal operations.

**Comment by Jak2k** [comment]
For what is it used exactly? Why is it not possible to use a solution like Matomo, which is privacy friendly and open source (and already used by EU institutions)?
