### ISSUE TITLE
QR Issuance with pid issuer

### ISSUE THREAD

**Issue by dariocast** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#98]
Hi, I am currently triyng to use this demo application with the PID Issuer at https://github.com/eu-digital-identity-wallet/eudi-srv-pid-issuer but I am unable to scan the QR Code properly. In the specific I built the application and run it on Oneplus 7, Android 12.

The National ID and sample document are ok to get but, if I build the pid issuer from https://github.com/eu-digital-identity-wallet/eudi-srv-pid-issuer and try to use it, i get this loop of error/warning and the scan does not produce anything:

```
05-24 11:22:31.148  1297  2261 E CamX    : [ERROR][STATS_AF] pdlib_sparse_wrapper.cpp:573 pd_process_center_window() lcr enable but raw image missing
05-24 11:22:31.182 30964 30964 W System.err: com.google.zxing.NotFoundException
```

I tried with every kind of format form the issuer, the outcome is the same.

How could I use that pid-issuer with this wallet, is not clear to me

**Comment by dariocast** [comment]
I read the other issue but it is not clear if, for example #73 refers to this kind of problem, so I reported a new Issue

**Comment by stzouvaras** [comment]
Hi  @dariocast,

the feature is not yet fully merged and developed. Please wait until the #73 is done and closed, hopefully, today or Monday EOD.

**Comment by dariocast** [comment]
I try reopening this issue as with the latest commit I was unable to overcome the issue. In the specific with the wallet I am unable to retrieve CredentialOffer from a running instance of pid-issuer from [that repo](https://github.com/eu-digital-identity-wallet/eudi-srv-pid-issuer).

I find out that the problem is that this line throws:
```
val credentialOffer = CredentialOfferRequestResolver().resolve(offerUri).getOrThrow()
```
from the core class DefaultOpenId4VciManager.kt.

Could you please provide some guidance on how to integrate correctly an issuer built from that repo?

I apologise if I reopen the issue, if I am off-topic or already answered
